### ISSUE TITLE
Make model/spec updates smooth in both UI and backend

### ISSUE THREAD

**Issue by Shreya-7** [Shreya-7/wardrobe-ui#4]
- should be minimum effort to update both UI and backend when we update the model or spec
- UI uses code gen, we should maybe not write our custom code in the generated code and explore an interface like approach?
- same for backend

**Comment by abhiandthetruth** [comment]
For backend the tooling seems insufficient tbh. For frontend we are not modifying the generated code, right?

**Comment by Shreya-7** [comment]
the only thing we modify as of now is the url of the backend.
for backend, we definitely have to come up with a pattern else everytime we generate code it will break everything, even the modifications we do in the generated code itself

**Comment by abhiandthetruth** [comment]
documentation of basic process of schema changes

**Comment by Shreya-7** [comment]
https://github.com/abhiandthetruth/wardrobe-api/wiki/Technical-Documentation
